/**
 * Catalog of ~10 dummy “sites” for Coact demo queue cards.
 * Used to generate forms, SOPs, and ~/Documents/Coact/queue cases.
 */

const DEMO_SITES = [
  {
    id: "northstar-job-apply",
    title: "Northstar Careers — Job application",
    siteName: "Northstar Careers",
    path: "sites/northstar-job-apply.html",
    accent: "#1d4ed8",
    fields: [
      { id: "fullName", label: "Full name", type: "text", valueFrom: "fullName" },
      { id: "email", label: "Email", type: "email", valueFrom: "email" },
      { id: "phone", label: "Phone", type: "tel", valueFrom: "phone" },
      { id: "role", label: "Role applying for", type: "text", valueFrom: "role" },
      { id: "years", label: "Years of experience", type: "text", valueFrom: "years" },
      { id: "linkedin", label: "LinkedIn URL", type: "url", valueFrom: "linkedin" },
      { id: "summary", label: "Why this role", type: "textarea", valueFrom: "summary" },
    ],
    answers: {
      fullName: "Ava Chen",
      email: "ava.chen@example.com",
      phone: "555-0101",
      role: "Frontend Engineer",
      years: "5",
      linkedin: "https://linkedin.com/in/avachen-demo",
      summary: "Built design systems and React apps for fintech dashboards.",
    },
  },
  {
    id: "riverdale-patient-intake",
    title: "Riverdale Clinic — Patient intake",
    siteName: "Riverdale Clinic",
    path: "sites/riverdale-patient-intake.html",
    accent: "#0f766e",
    fields: [
      { id: "patientName", label: "Patient name", type: "text", valueFrom: "patientName" },
      { id: "dob", label: "Date of birth", type: "text", valueFrom: "dob" },
      { id: "email", label: "Email", type: "email", valueFrom: "email" },
      { id: "phone", label: "Phone", type: "tel", valueFrom: "phone" },
      { id: "reason", label: "Reason for visit", type: "text", valueFrom: "reason" },
      { id: "allergies", label: "Allergies", type: "text", valueFrom: "allergies" },
      { id: "insurance", label: "Insurance provider", type: "text", valueFrom: "insurance" },
    ],
    answers: {
      patientName: "Marcus Webb",
      dob: "1990-04-12",
      email: "marcus.webb@example.com",
      phone: "555-0102",
      reason: "Annual checkup",
      allergies: "Penicillin",
      insurance: "Blue Shield Demo",
    },
  },
  {
    id: "summit-event-rsvp",
    title: "Summit Conference — Event RSVP",
    siteName: "Summit Conference",
    path: "sites/summit-event-rsvp.html",
    accent: "#7c3aed",
    fields: [
      { id: "attendeeName", label: "Attendee name", type: "text", valueFrom: "attendeeName" },
      { id: "email", label: "Email", type: "email", valueFrom: "email" },
      { id: "company", label: "Company", type: "text", valueFrom: "company" },
      { id: "ticket", label: "Ticket type", type: "text", valueFrom: "ticket" },
      { id: "dietary", label: "Dietary needs", type: "text", valueFrom: "dietary" },
      { id: "sessions", label: "Sessions of interest", type: "textarea", valueFrom: "sessions" },
    ],
    answers: {
      attendeeName: "Priya Nair",
      email: "priya.nair@example.com",
      company: "Orbit Labs",
      ticket: "Full conference pass",
      dietary: "Vegetarian",
      sessions: "AI keynote; Product ops workshop; Networking mixer",
    },
  },
  {
    id: "cloudhelp-support",
    title: "CloudHelp Desk — Support ticket",
    siteName: "CloudHelp Desk",
    path: "sites/cloudhelp-support.html",
    accent: "#b45309",
    fields: [
      { id: "reporter", label: "Your name", type: "text", valueFrom: "reporter" },
      { id: "email", label: "Work email", type: "email", valueFrom: "email" },
      { id: "product", label: "Product", type: "text", valueFrom: "product" },
      { id: "severity", label: "Severity", type: "text", valueFrom: "severity" },
      { id: "subject", label: "Subject", type: "text", valueFrom: "subject" },
      { id: "details", label: "Issue details", type: "textarea", valueFrom: "details" },
    ],
    answers: {
      reporter: "Diego Morales",
      email: "diego@orbitlabs.example",
      product: "Billing Console",
      severity: "High",
      subject: "Invoice PDF export fails",
      details: "Export hangs at 80% for accounts created before 2024. Browser console shows 504.",
    },
  },
  {
    id: "greenpath-volunteer",
    title: "GreenPath — Volunteer signup",
    siteName: "GreenPath Nonprofit",
    path: "sites/greenpath-volunteer.html",
    accent: "#15803d",
    fields: [
      { id: "name", label: "Full name", type: "text", valueFrom: "name" },
      { id: "email", label: "Email", type: "email", valueFrom: "email" },
      { id: "phone", label: "Phone", type: "tel", valueFrom: "phone" },
      { id: "city", label: "City", type: "text", valueFrom: "city" },
      { id: "availability", label: "Availability", type: "text", valueFrom: "availability" },
      { id: "skills", label: "Skills", type: "textarea", valueFrom: "skills" },
    ],
    answers: {
      name: "Elena Park",
      email: "elena.park@example.com",
      phone: "555-0105",
      city: "Portland",
      availability: "Weekends 9am–1pm",
      skills: "Trail maintenance, event setup, Spanish conversational",
    },
  },
  {
    id: "harborview-booking",
    title: "Harborview Inn — Booking inquiry",
    siteName: "Harborview Inn",
    path: "sites/harborview-booking.html",
    accent: "#0369a1",
    fields: [
      { id: "guestName", label: "Guest name", type: "text", valueFrom: "guestName" },
      { id: "email", label: "Email", type: "email", valueFrom: "email" },
      { id: "checkIn", label: "Check-in date", type: "text", valueFrom: "checkIn" },
      { id: "checkOut", label: "Check-out date", type: "text", valueFrom: "checkOut" },
      { id: "guests", label: "Number of guests", type: "text", valueFrom: "guests" },
      { id: "roomType", label: "Room type", type: "text", valueFrom: "roomType" },
      { id: "notes", label: "Special requests", type: "textarea", valueFrom: "notes" },
    ],
    answers: {
      guestName: "Noah Bennett",
      email: "noah.bennett@example.com",
      checkIn: "2026-09-12",
      checkOut: "2026-09-15",
      guests: "2",
      roomType: "Ocean view king",
      notes: "Late check-in around 10pm; quiet floor preferred.",
    },
  },
  {
    id: "openlearn-enroll",
    title: "OpenLearn Academy — Course enrollment",
    siteName: "OpenLearn Academy",
    path: "sites/openlearn-enroll.html",
    accent: "#c2410c",
    fields: [
      { id: "studentName", label: "Student name", type: "text", valueFrom: "studentName" },
      { id: "email", label: "Email", type: "email", valueFrom: "email" },
      { id: "course", label: "Course name", type: "text", valueFrom: "course" },
      { id: "term", label: "Term", type: "text", valueFrom: "term" },
      { id: "level", label: "Experience level", type: "text", valueFrom: "level" },
      { id: "goals", label: "Learning goals", type: "textarea", valueFrom: "goals" },
    ],
    answers: {
      studentName: "Sofia Alvarez",
      email: "sofia.alvarez@example.com",
      course: "Intro to Data Analytics",
      term: "Fall 2026",
      level: "Beginner",
      goals: "Learn SQL basics and build a portfolio dashboard.",
    },
  },
  {
    id: "shieldcare-claim",
    title: "ShieldCare — Insurance claim intake",
    siteName: "ShieldCare Insurance",
    path: "sites/shieldcare-claim.html",
    accent: "#be123c",
    fields: [
      { id: "policyHolder", label: "Policy holder", type: "text", valueFrom: "policyHolder" },
      { id: "policyNumber", label: "Policy number", type: "text", valueFrom: "policyNumber" },
      { id: "email", label: "Email", type: "email", valueFrom: "email" },
      { id: "incidentDate", label: "Incident date", type: "text", valueFrom: "incidentDate" },
      { id: "claimType", label: "Claim type", type: "text", valueFrom: "claimType" },
      { id: "description", label: "What happened", type: "textarea", valueFrom: "description" },
    ],
    answers: {
      policyHolder: "James Okonkwo",
      policyNumber: "SC-448291",
      email: "james.okonkwo@example.com",
      incidentDate: "2026-07-01",
      claimType: "Auto — minor collision",
      description: "Rear-ended at stoplight; police report filed; photos available.",
    },
  },
  {
    id: "pulse-feedback",
    title: "Pulse — Customer feedback survey",
    siteName: "Pulse Feedback",
    path: "sites/pulse-feedback.html",
    accent: "#4f46e5",
    fields: [
      { id: "name", label: "Your name", type: "text", valueFrom: "name" },
      { id: "email", label: "Email", type: "email", valueFrom: "email" },
      { id: "product", label: "Product used", type: "text", valueFrom: "product" },
      { id: "rating", label: "Satisfaction (1-10)", type: "text", valueFrom: "rating" },
      { id: "liked", label: "What worked well", type: "textarea", valueFrom: "liked" },
      { id: "improve", label: "What to improve", type: "textarea", valueFrom: "improve" },
    ],
    answers: {
      name: "Hannah Brooks",
      email: "hannah.brooks@example.com",
      product: "liveAct Desktop",
      rating: "8",
      liked: "Step tracking and attended fill are clear.",
      improve: "Faster snippet capture and quieter status notes.",
    },
  },
  {
    id: "metro-permit",
    title: "Metro City — Permit application",
    siteName: "Metro City Permits",
    path: "sites/metro-permit.html",
    accent: "#475569",
    fields: [
      { id: "applicant", label: "Applicant name", type: "text", valueFrom: "applicant" },
      { id: "email", label: "Email", type: "email", valueFrom: "email" },
      { id: "address", label: "Property address", type: "text", valueFrom: "address" },
      { id: "permitType", label: "Permit type", type: "text", valueFrom: "permitType" },
      { id: "startDate", label: "Proposed start date", type: "text", valueFrom: "startDate" },
      { id: "scope", label: "Project scope", type: "textarea", valueFrom: "scope" },
    ],
    answers: {
      applicant: "Taylor Kim",
      email: "taylor.kim@example.com",
      address: "88 Cedar Lane, Metro City",
      permitType: "Residential renovation",
      startDate: "2026-10-01",
      scope: "Kitchen remodel; no structural changes; licensed contractor on file.",
    },
  },
];

module.exports = { DEMO_SITES };
